# Generated by Django 2.2.10 on 2020-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingslite',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(max_length=60)),
                ('when', models.DateTimeField(max_length=60)),
                ('short_code', models.CharField(max_length=60)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('position', models.CharField(max_length=500, null=True)),
                ('parking_found', models.BooleanField(max_length=500, null=True)),
                ('selected_name', models.CharField(max_length=500, null=True)),
                ('trello_url', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'bookingslite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parkings',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lmpPID', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=500, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'db_table': 'parkings',
                'managed': False,
            },
        ),
    ]
